### ISSUE TITLE
Possible leak in KNITRO 9.0.1

### ISSUE THREAD

**Issue by bchretien** [roboptim/roboptim-core-plugin-knitro#3]
I implemented a system that waits until a license is available (for those poor souls sharing a single network license). AFAIK, the only way to do this is to loop over `KTR_new()` and check the returned pointer. [The official doc](https://www.artelys.com/tools/knitro_doc/3_referenceManual/callableLibrary/API.html) says:

``` txt
KTR_new()

KTR_context_ptr  KNITRO_API KTR_new (void);

This function must be called first. It returns a pointer to an object (the
Knitro “context pointer”) that is used in all other calls. If you enable Knitro
with the Ziena floating network license handler, then this call also checks out
a license and reserves it until KTR_free() is called with the context pointer,
or the program ends. The contents of the context pointer should never be
modified by a calling program. Returns NULL on error.
```

Thus, I loop until the returned pointer is not `NULL`, with a parametrized sleep time. I recently noticed an unusual memory usage when waiting for a license, as was confirmed by valgrind's massif:

![wtf](https://cloud.githubusercontent.com/assets/2742231/12741814/2ff24b32-c9c3-11e5-83e9-0a745420d929.png)

At first I assumed that something was wrong in the `stderr` redirection I had to implement to avoid being spammed, but apparently not...

This was tested with KNITRO 9.0.1 on Linux 64bit.

**Comment by bchretien** [comment]
Since there's apparently nothing we can do about it, I reduced the checking rate and added a maximum number of retries with a `runtime_error` thrown at the end in case of failure.

![wtf2](https://cloud.githubusercontent.com/assets/2742231/12742315/f7b49e50-c9c7-11e5-99ce-d7f3102d696f.png)

The C++ API may provide a way to circumvent this issue (unless it's a simple wrapper around the C API), but a) the C++ API is not available in that version, and b) the issue may have been resolved in the following releases.

**Comment by bchretien** [comment]
Possible workaround: using their _high volume license functions_, i.e.:

``` text
Two special functions are provided with the Knitro callable library
programmatic interface: ZLM_checkout_license and ZLM_release_license. An
application program may call these functions (from C, C++, or Java) to obtain a
single floating license and reuse it to start a sequence of Knitro instances.
If the application needs to run multiple concurrent Knitro instances, then it
must check out enough licenses to support the maximum number of concurrent
instances.
```

These functions are called before `KTR_new*`.

**Comment by bchretien** [comment]
Actually, `KTR_new_zlm` needs to be called in the loop since "_the license will be checked out the first time KTR_new_zlm is called_", but that function does not seem to be leaking, so it's solved.

**Comment by thomas-moulard** [comment]
If I were you I would wait in a separate process. Ideally forking once the token is available would be a good solution.

**Comment by bchretien** [comment]
Well it should be fixed now, I'm pretty sure the leak was due to the license manager memory that was allocated and never released in the basic `KTR_new` function. Plus we should be using the most recent version soon, and I guess they fixed that since then.
